--- #YAML:1.0
name:                Lingua-JA-FindDates
version:             0.004
abstract:            find Japanese dates & convert them
license:             ~
author:              
    - Ben Bullock <benkasminbullock@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
